pub type OpcodeSpec = (&'static str, u8, u8, Option<(&'static str, u8)>);
pub type RegSpec = (&'static str, &'static [(&'static str, u8)]);
pub type InsnSpec<'a> = (&'static str, &'static str, u8, &'a [&'static str]);
pub type RegNames = (&'static str, [&'static str; 32], [&'static str; 32]);
pub type PseudoSpec = (
    &'static str,
    &'static [&'static str],
    &'static str,
    &'static [&'static str],
);

pub const PSEUDO_SPEC: &'static [PseudoSpec] = &[
    ("LI", &["Rt", "Imm"], "ADDIU", &["Rt", "zero", "Imm"]),
    (
        "B",
        &["BranchTarget"],
        "BEQ",
        &["zero", "zero", "BranchTarget"],
    ),
    ("MOVE", &["Rd", "Rs"], "OR", &["Rd", "Rs", "zero"]),
];

pub const SPEC: (&[OpcodeSpec], &[RegSpec], &[InsnSpec], &[RegNames]) = (
    // Opcode kinds
    &[
        ("Regular", 26, 6, None),
        ("Special", 0, 6, Some(("Regular", 0))),
        ("Regimm", 16, 5, Some(("Regular", 1))),
        ("Cop0", 21, 5, Some(("Regular", 16))),
        ("Tlb", 0, 6, Some(("Cop0", 16))),
        ("Cop1", 21, 5, Some(("Regular", 17))),
        ("Bc", 16, 3, Some(("Cop1", 8))),
        ("FpS", 0, 6, Some(("Cop1", 16))),
        ("FpD", 0, 6, Some(("Cop1", 17))),
        ("FpW", 0, 6, Some(("Cop1", 20))),
        ("FpL", 0, 6, Some(("Cop1", 21))),
    ],
    // Regs
    &[
        ("Gp", &[("Base", 21), ("Rs", 21), ("Rt", 16), ("Rd", 11)]),
        ("Fp", &[("Ft", 16), ("Fs", 11), ("Fd", 6)]),
        ("Fc", &[("FcrRd", 11)]),
        ("C0", &[("Cop0Rd", 11)]),
    ],
    // Instructions
    &[
        ("Regular", "LUI", 15, &["Rt", "VerbatimImm"]),
        ("Regular", "CACHE", 47, &["CacheOp", "Displace"]),
        ("Regular", "J", 2, &["JumpTarget"]),
        ("Regular", "JAL", 3, &["JumpTarget"]),
        ("Regular", "ANDI", 12, &["Rt", "Rs", "VerbatimImm"]),
        ("Regular", "ORI", 13, &["Rt", "Rs", "VerbatimImm"]),
        ("Regular", "XORI", 14, &["Rt", "Rs", "VerbatimImm"]),
        ("Regular", "BEQ", 4, &["Rs", "Rt", "BranchTarget"]),
        ("Regular", "BNE", 5, &["Rs", "Rt", "BranchTarget"]),
        ("Regular", "BEQL", 20, &["Rs", "Rt", "BranchTarget"]),
        ("Regular", "BNEL", 21, &["Rs", "Rt", "BranchTarget"]),
        ("Regular", "BLEZ", 6, &["Rs", "BranchTarget"]),
        ("Regular", "BGTZ", 7, &["Rs", "BranchTarget"]),
        ("Regular", "BLEZL", 22, &["Rs", "BranchTarget"]),
        ("Regular", "BGTZL", 23, &["Rs", "BranchTarget"]),
        ("Regular", "ADDI", 8, &["Rt", "Rs", "Imm"]),
        ("Regular", "ADDIU", 9, &["Rt", "Rs", "Imm"]),
        ("Regular", "SLTI", 10, &["Rt", "Rs", "Imm"]),
        ("Regular", "SLTIU", 11, &["Rt", "Rs", "Imm"]),
        ("Regular", "DADDI", 24, &["Rt", "Rs", "Imm"]),
        ("Regular", "DADDIU", 25, &["Rt", "Rs", "Imm"]),
        ("Regular", "LDL", 26, &["Rt", "Displace"]),
        ("Regular", "LDR", 27, &["Rt", "Displace"]),
        ("Regular", "LB", 32, &["Rt", "Displace"]),
        ("Regular", "LH", 33, &["Rt", "Displace"]),
        ("Regular", "LWL", 34, &["Rt", "Displace"]),
        ("Regular", "LW", 35, &["Rt", "Displace"]),
        ("Regular", "LBU", 36, &["Rt", "Displace"]),
        ("Regular", "LHU", 37, &["Rt", "Displace"]),
        ("Regular", "LWR", 38, &["Rt", "Displace"]),
        ("Regular", "LWU", 39, &["Rt", "Displace"]),
        ("Regular", "SB", 40, &["Rt", "Displace"]),
        ("Regular", "SH", 41, &["Rt", "Displace"]),
        ("Regular", "SWL", 42, &["Rt", "Displace"]),
        ("Regular", "SW", 43, &["Rt", "Displace"]),
        ("Regular", "SDL", 44, &["Rt", "Displace"]),
        ("Regular", "SDR", 45, &["Rt", "Displace"]),
        ("Regular", "SWR", 46, &["Rt", "Displace"]),
        ("Regular", "LL", 48, &["Rt", "Displace"]),
        ("Regular", "LWC1", 49, &["Ft", "Displace"]),
        ("Regular", "LLD", 52, &["Rt", "Displace"]),
        ("Regular", "LDC1", 53, &["Ft", "Displace"]),
        ("Regular", "LD", 55, &["Rt", "Displace"]),
        ("Regular", "SC", 56, &["Rt", "Displace"]),
        ("Regular", "SWC1", 57, &["Ft", "Displace"]),
        ("Regular", "SCD", 60, &["Rt", "Displace"]),
        ("Regular", "SDC1", 61, &["Ft", "Displace"]),
        ("Regular", "SD", 63, &["Rt", "Displace"]),
        // fpu single
        ("FpS", "ADD_S", 0, &["Fd", "Fs", "Ft"]),
        ("FpS", "SUB_S", 1, &["Fd", "Fs", "Ft"]),
        ("FpS", "MUL_S", 2, &["Fd", "Fs", "Ft"]),
        ("FpS", "DIV_S", 3, &["Fd", "Fs", "Ft"]),
        ("FpS", "SQRT_S", 4, &["Fd", "Fs"]),
        ("FpS", "ABS_S", 5, &["Fd", "Fs"]),
        ("FpS", "MOV_S", 6, &["Fd", "Fs"]),
        ("FpS", "NEG_S", 7, &["Fd", "Fs"]),
        ("FpS", "ROUND_L_S", 8, &["Fd", "Fs"]),
        ("FpS", "TRUNC_L_S", 9, &["Fd", "Fs"]),
        ("FpS", "CEIL_L_S", 10, &["Fd", "Fs"]),
        ("FpS", "FLOOR_L_S", 11, &["Fd", "Fs"]),
        ("FpS", "ROUND_W_S", 12, &["Fd", "Fs"]),
        ("FpS", "TRUNC_W_S", 13, &["Fd", "Fs"]),
        ("FpS", "CEIL_W_S", 14, &["Fd", "Fs"]),
        ("FpS", "FLOOR_W_S", 15, &["Fd", "Fs"]),
        ("FpS", "CVT_D_S", 33, &["Fd", "Fs"]),
        ("FpS", "CVT_W_S", 36, &["Fd", "Fs"]),
        ("FpS", "CVT_L_S", 37, &["Fd", "Fs"]),
        ("FpS", "C_F_S", 48, &["Fs", "Ft"]),
        ("FpS", "C_UN_S", 49, &["Fs", "Ft"]),
        ("FpS", "C_EQ_S", 50, &["Fs", "Ft"]),
        ("FpS", "C_UEQ_S", 51, &["Fs", "Ft"]),
        ("FpS", "C_OLT_S", 52, &["Fs", "Ft"]),
        ("FpS", "C_ULT_S", 53, &["Fs", "Ft"]),
        ("FpS", "C_OLE_S", 54, &["Fs", "Ft"]),
        ("FpS", "C_ULE_S", 55, &["Fs", "Ft"]),
        ("FpS", "C_SF_S", 56, &["Fs", "Ft"]),
        ("FpS", "C_NGLE_S", 57, &["Fs", "Ft"]),
        ("FpS", "C_SEQ_S", 58, &["Fs", "Ft"]),
        ("FpS", "C_NGL_S", 59, &["Fs", "Ft"]),
        ("FpS", "C_LT_S", 60, &["Fs", "Ft"]),
        ("FpS", "C_NGE_S", 61, &["Fs", "Ft"]),
        ("FpS", "C_LE_S", 62, &["Fs", "Ft"]),
        ("FpS", "C_NGT_S", 63, &["Fs", "Ft"]),
        // fpu double
        ("FpD", "ADD_D", 0, &["Fd", "Fs", "Ft"]),
        ("FpD", "SUB_D", 1, &["Fd", "Fs", "Ft"]),
        ("FpD", "MUL_D", 2, &["Fd", "Fs", "Ft"]),
        ("FpD", "DIV_D", 3, &["Fd", "Fs", "Ft"]),
        ("FpD", "SQRT_D", 4, &["Fs", "Fd"]),
        ("FpD", "ABS_D", 5, &["Fs", "Fd"]),
        ("FpD", "MOV_D", 6, &["Fs", "Fd"]),
        ("FpD", "NEG_D", 7, &["Fs", "Fd"]),
        ("FpD", "ROUND_L_D", 8, &["Fs", "Fd"]),
        ("FpD", "TRUNC_L_D", 9, &["Fs", "Fd"]),
        ("FpD", "CEIL_L_D", 10, &["Fs", "Fd"]),
        ("FpD", "FLOOR_L_D", 11, &["Fs", "Fd"]),
        ("FpD", "ROUND_W_D", 12, &["Fs", "Fd"]),
        ("FpD", "TRUNC_W_D", 13, &["Fs", "Fd"]),
        ("FpD", "CEIL_W_D", 14, &["Fs", "Fd"]),
        ("FpD", "FLOOR_W_D", 15, &["Fs", "Fd"]),
        ("FpD", "CVT_S_D", 32, &["Fs", "Fd"]),
        ("FpD", "CVT_W_D", 36, &["Fs", "Fd"]),
        ("FpD", "CVT_L_D", 37, &["Fs", "Fd"]),
        ("FpD", "C_F_D", 48, &["Fs", "Ft"]),
        ("FpD", "C_UN_D", 49, &["Fs", "Ft"]),
        ("FpD", "C_EQ_D", 50, &["Fs", "Ft"]),
        ("FpD", "C_UEQ_D", 51, &["Fs", "Ft"]),
        ("FpD", "C_OLT_D", 52, &["Fs", "Ft"]),
        ("FpD", "C_ULT_D", 53, &["Fs", "Ft"]),
        ("FpD", "C_OLE_D", 54, &["Fs", "Ft"]),
        ("FpD", "C_ULE_D", 55, &["Fs", "Ft"]),
        ("FpD", "C_SF_D", 56, &["Fs", "Ft"]),
        ("FpD", "C_NGLE_D", 57, &["Fs", "Ft"]),
        ("FpD", "C_SEQ_D", 58, &["Fs", "Ft"]),
        ("FpD", "C_NGL_D", 59, &["Fs", "Ft"]),
        ("FpD", "C_LT_D", 60, &["Fs", "Ft"]),
        ("FpD", "C_NGE_D", 61, &["Fs", "Ft"]),
        ("FpD", "C_LE_D", 62, &["Fs", "Ft"]),
        ("FpD", "C_NGT_D", 63, &["Fs", "Ft"]),
        ("Special", "SLL", 0, &["Rd", "Rt", "ShiftAmount"]),
        ("Special", "SRL", 2, &["Rd", "Rt", "ShiftAmount"]),
        ("Special", "SRA", 3, &["Rd", "Rt", "ShiftAmount"]),
        ("Special", "SLLV", 4, &["Rd", "Rs", "Rt"]),
        ("Special", "SRLV", 6, &["Rd", "Rs", "Rt"]),
        ("Special", "SRAV", 7, &["Rd", "Rs", "Rt"]),
        ("Special", "JR", 8, &["Rs"]),
        ("Special", "JALR", 9, &["Rd", "Rs"]),
        ("Special", "SYSCALL", 12, &["SyscallCode"]),
        ("Special", "BREAK", 13, &["BreakCode"]),
        ("Special", "SYNC", 15, &[]),
        ("Special", "MFHI", 16, &["Rd"]),
        ("Special", "MTHI", 17, &["Rs"]),
        ("Special", "MFLO", 18, &["Rd"]),
        ("Special", "MTLO", 19, &["Rs"]),
        ("Special", "DSLLV", 20, &["Rd", "Rs", "Rt"]),
        ("Special", "DSRLV", 22, &["Rd", "Rs", "Rt"]),
        ("Special", "DSRAV", 23, &["Rd", "Rs", "Rt"]),
        ("Special", "MULT", 24, &["Rs", "Rt"]),
        ("Special", "MULTU", 25, &["Rs", "Rt"]),
        ("Special", "DIV", 26, &["Rs", "Rt"]),
        ("Special", "DIVU", 27, &["Rs", "Rt"]),
        ("Special", "DMULT", 28, &["Rs", "Rt"]),
        ("Special", "DMULTU", 29, &["Rs", "Rt"]),
        ("Special", "DDIV", 30, &["Rs", "Rt"]),
        ("Special", "DDIVU", 31, &["Rs", "Rt"]),
        ("Special", "ADD", 32, &["Rd", "Rs", "Rt"]),
        ("Special", "ADDU", 33, &["Rd", "Rs", "Rt"]),
        ("Special", "SUB", 34, &["Rd", "Rs", "Rt"]),
        ("Special", "SUBU", 35, &["Rd", "Rs", "Rt"]),
        ("Special", "AND", 36, &["Rd", "Rs", "Rt"]),
        ("Special", "OR", 37, &["Rd", "Rs", "Rt"]),
        ("Special", "XOR", 38, &["Rd", "Rs", "Rt"]),
        ("Special", "NOR", 39, &["Rd", "Rs", "Rt"]),
        ("Special", "SLT", 42, &["Rd", "Rs", "Rt"]),
        ("Special", "SLTU", 43, &["Rd", "Rs", "Rt"]),
        ("Special", "DADD", 44, &["Rd", "Rs", "Rt"]),
        ("Special", "DADDU", 45, &["Rd", "Rs", "Rt"]),
        ("Special", "DSUB", 46, &["Rd", "Rs", "Rt"]),
        ("Special", "DSUBU", 47, &["Rd", "Rs", "Rt"]),
        ("Special", "TGE", 48, &["Rs", "Rt"]),
        ("Special", "TGEU", 49, &["Rs", "Rt"]),
        ("Special", "TLT", 50, &["Rs", "Rt"]),
        ("Special", "TLTU", 51, &["Rs", "Rt"]),
        ("Special", "TEQ", 52, &["Rs", "Rt"]),
        ("Special", "TNE", 54, &["Rs", "Rt"]),
        ("Special", "DSLL", 56, &["Rd", "Rt", "ShiftAmount"]),
        ("Special", "DSRL", 58, &["Rd", "Rt", "ShiftAmount"]),
        ("Special", "DSRA", 59, &["Rd", "Rt", "ShiftAmount"]),
        ("Special", "DSLL32", 60, &["Rd", "Rt", "ShiftAmount"]),
        ("Special", "DSRL32", 62, &["Rd", "Rt", "ShiftAmount"]),
        ("Special", "DSRA32", 63, &["Rd", "Rt", "ShiftAmount"]),
        ("Regimm", "BLTZ", 0, &["Rs", "BranchTarget"]),
        ("Regimm", "BGEZ", 1, &["Rs", "BranchTarget"]),
        ("Regimm", "BLTZL", 2, &["Rs", "BranchTarget"]),
        ("Regimm", "BGEZL", 3, &["Rs", "BranchTarget"]),
        ("Regimm", "TGEI", 8, &["Rs", "Imm"]),
        ("Regimm", "TGEIU", 9, &["Rs", "Imm"]),
        ("Regimm", "TLTI", 10, &["Rs", "Imm"]),
        ("Regimm", "TLTIU", 11, &["Rs", "Imm"]),
        ("Regimm", "TEQI", 12, &["Rs", "Imm"]),
        ("Regimm", "TNEI", 14, &["Rs", "Imm"]),
        ("Regimm", "BLTZAL", 16, &["Rs", "BranchTarget"]),
        ("Regimm", "BGEZAL", 17, &["Rs", "BranchTarget"]),
        ("Regimm", "BLTZALL", 18, &["Rs", "BranchTarget"]),
        ("Regimm", "BGEZALL", 19, &["Rs", "BranchTarget"]),
        ("Cop0", "MFC0", 0, &["Rt", "Cop0Rd"]),
        ("Cop0", "DMFC0", 1, &["Rt", "Cop0Rd"]),
        ("Cop0", "MTC0", 3, &["Rt", "Cop0Rd"]),
        ("Cop0", "DMTC0", 4, &["Rt", "Cop0Rd"]),
        ("Tlb", "TLBR", 1, &[]),
        ("Tlb", "TLBWI", 2, &[]),
        ("Tlb", "TLBWR", 6, &[]),
        ("Tlb", "TLBP", 8, &[]),
        ("Tlb", "ERET", 24, &[]),
        ("Cop1", "MFC1", 0, &["Rt", "Fs"]),
        ("Cop1", "DMFC1", 1, &["Rt", "Fs"]),
        ("Cop1", "CFC1", 2, &["Rt", "FcrRd"]),
        ("Cop1", "MTC1", 4, &["Rt", "Fs"]),
        ("Cop1", "DMTC1", 5, &["Rt", "Fs"]),
        ("Cop1", "CTC1", 6, &["Rt", "FcrRd"]),
        ("Bc", "BC1F", 0, &["BranchTarget"]),
        ("Bc", "BC1T", 1, &["BranchTarget"]),
        ("Bc", "BC1FL", 2, &["BranchTarget"]),
        ("Bc", "BC1TL", 3, &["BranchTarget"]),
        ("FpL", "CVT_S_L", 32, &["Fd", "Fs"]),
        ("FpL", "CVT_D_L", 33, &["Fd", "Fs"]),
        ("FpW", "CVT_S_W", 32, &["Fd", "Fs"]),
        ("FpW", "CVT_D_W", 33, &["Fd", "Fs"]),
    ],
    &[
        (
            "Gp",
            [
                "Zero", "At", "V0", "V1", "A0", "A1", "A2", "A3", "T0", "T1", "T2", "T3", "T4",
                "T5", "T6", "T7", "S0", "S1", "S2", "S3", "S4", "S5", "S6", "S7", "T8", "T9", "K0",
                "K1", "Gp", "Sp", "S8", "Ra",
            ],
            [
                "$zero", "$at", "v0", "v1", "a0", "a1", "a2", "a3", "t0", "t1", "t2", "t3", "t4",
                "t5", "t6", "t7", "s0", "s1", "s2", "s3", "s4", "s5", "s6", "s7", "t8", "t9", "k0",
                "k1", "$gp", "$sp", "s8", "$ra",
            ],
        ),
        (
            "Fp",
            [
                "F0", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12",
                "F13", "F14", "F15", "F16", "F17", "F18", "F19", "F20", "F21", "F22", "F23", "F24",
                "F25", "F26", "F27", "F28", "F29", "F30", "F31",
            ],
            [
                "$f0", "$f1", "$f2", "$f3", "$f4", "$f5", "$f6", "$f7", "$f8", "$f9", "$f10",
                "$f11", "$f12", "$f13", "$f14", "$f15", "$f16", "$f17", "$f18", "$f19", "$f20",
                "$f21", "$f22", "$f23", "$f24", "$f25", "$f26", "$f27", "$f28", "$f29", "$f30",
                "$f31",
            ],
        ),
        (
            "Fc",
            [
                "FC_IMPL",
                "FC1",
                "FC2",
                "FC3",
                "FC4",
                "FC5",
                "FC6",
                "FC7",
                "FC8",
                "FC9",
                "FC10",
                "FC11",
                "FC12",
                "FC13",
                "FC14",
                "FC15",
                "FC16",
                "FC17",
                "FC18",
                "FC19",
                "FC20",
                "FC21",
                "FC22",
                "FC23",
                "FC24",
                "FC25",
                "FC26",
                "FC27",
                "FC28",
                "FC29",
                "FC30",
                "FC_STATUS",
            ],
            [
                "FC_IMPL",
                "FC1",
                "FC2",
                "FC3",
                "FC4",
                "FC5",
                "FC6",
                "FC7",
                "FC8",
                "FC9",
                "FC10",
                "FC11",
                "FC12",
                "FC13",
                "FC14",
                "FC15",
                "FC16",
                "FC17",
                "FC18",
                "FC19",
                "FC20",
                "FC21",
                "FC22",
                "FC23",
                "FC24",
                "FC25",
                "FC26",
                "FC27",
                "FC28",
                "FC29",
                "FC30",
                "FC_STATUS",
            ],
        ),
        (
            "C0",
            [
                "C0_INX",
                "C0_RAND",
                "C0_ENTRYLO0",
                "C0_ENTRYLO1",
                "C0_CONTEXT",
                "C0_PAGEMASK",
                "C0_WIRED",
                "C0_7",
                "C0_BADVADDR",
                "C0_COUNT",
                "C0_ENTRYHI",
                "C0_COMPARE",
                "C0_SR",
                "C0_CAUSE",
                "C0_EPC",
                "C0_PRID",
                "C0_CONFIG",
                "C0_LLADDR",
                "C0_WATCHLO",
                "C0_WATCHHI",
                "C0_20",
                "C0_21",
                "C0_22",
                "C0_23",
                "C0_24",
                "C0_25",
                "C0_ECC",
                "C0_CACHE_ERR",
                "C0_TAGLO",
                "C0_TAGHI",
                "C0_ERROR_EPC",
                "C0_31",
            ],
            [
                "C0_INX",
                "C0_RAND",
                "C0_ENTRYLO0",
                "C0_ENTRYLO1",
                "C0_CONTEXT",
                "C0_PAGEMASK",
                "C0_WIRED",
                "C0_7",
                "C0_BADVADDR",
                "C0_COUNT",
                "C0_ENTRYHI",
                "C0_COMPARE",
                "C0_SR",
                "C0_CAUSE",
                "C0_EPC",
                "C0_PRID",
                "C0_CONFIG",
                "C0_LLADDR",
                "C0_WATCHLO",
                "C0_WATCHHI",
                "C0_20",
                "C0_21",
                "C0_22",
                "C0_23",
                "C0_24",
                "C0_25",
                "C0_ECC",
                "C0_CACHE_ERR",
                "C0_TAGLO",
                "C0_TAGHI",
                "C0_ERROR_EPC",
                "C0_31",
            ],
        ),
    ],
);
