[package]
name = "disasm-rom"
version = "0.1.0"
authors = ["Kjartan Skjervøy <kskjer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reality-mips = { path = "../../lib/reality-mips" }
reality-ultra = { path = "../../lib/reality-ultra" }
