[package]
name = "file-list"
version = "0.1.0"
authors = ["Kjartan Skjervoy <kskjer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reality-mips = { path = "../../lib/reality-mips" }
reality-util = { path = "../../lib/reality-util" }
reality-ultra = { path = "../../lib/reality-ultra" }
reality-zelda = { path = "../../lib/reality-zelda" }

