[package]
name = "rom-to-v64"
version = "0.1.0"
authors = ["Kjartan Skjervoy <kskjer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
